baseurl = "http://girlswithdeeppockets.com/"
languageCode = "en-gb"
title = "Girls with Deep Pockets"
# Enable comments by entering your Disqus shortname
disqusShortname = "girlswithdeeppockets"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-86386589-1"
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "↩"
theme = "hugo-icarus-theme"


[permalinks]
    post = "/:slug"


[params]
    # Tell me who you are
    author = "Girls with Deep Pockets"
    bio = "A site for celebrating clothes with pockets"
    location = "Utopia, where stuff fits in pockets"
    site_description = "A site celebrating items of women's clothing you can fit a modern phone in!"
    copyright  = "Stephanie Locke. Site made using [Hugo](//gohugo.io) and the [Icarus](https://github.com/digitalcraftsman/hugo-icarus-theme) theme."
    avatar = "imgs/gwdplogolight.png"
    logo = "imgs/gwdplogolight.png"

    # Format dates with Go's time formatting
    date_format = "2006-01-02"

# Create custom menu entries by defining a label and a link for
# them. Since you can also link posts, you've the option the
# place the links before or after them.
#
# E.g.: "Home" appears before all linked posts in the menu
# and "Tags" / "Categories" after them.
[[params.menu]]
    before = true
    label  = "Home"
    link   = "/"

#[[params.menu]]
#    before = false
#    label  = "Tags"
#    link   = "tags/"
#
#[[params.menu]]
#    before = false
#    label  = "Categories"
#    link   = "categories/"

# Enter a link for the follow button on the left
[params.profile]
    follow_button = "https://twitter.com/gwdeeppockets"


email = "your@email.com"

[social]
# Add your social network accounts to the profile section on the left
# by entering your username. The links to your account will be
# created automatically.
    github          = "stephlocke/girlswithdeeppockets"
    gitlab          = ""
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = ""
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    linkedin        = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = ""
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "gwdeeppockets"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true
